#!/usr/bin/env Rscript

install.packages("usethis")
install.packages("devtools")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("markdown")
install.packages("shinyjs")
install.packages("shinybusy")
install.packages("Seurat")
install.packages("ggplot2")
install.packages("plotly")
install.packages("tools")
install.packages("dplyr")
install.packages("DT")
install.packages("shinydashboardPlus")
install.packages("glue")
install.packages("markdown")
install.packages("ggthemes")



library(shiny)
library(shinydashboard)
library(markdown)
library(shinyjs)
library(shinybusy)
library(Seurat)
library(ggplot2)
library(plotly)
library(tools)
library(dplyr)
library(DT)
library(shinydashboardPlus)
library(glue)
library(markdown)
library(ggthemes)
library(usethis)
library(devtools)

install_github("BTIP2024/write-seurat-object")
install_github("BTIP2024/quality-control-seurat")
install_github("BTIP2024/selection-scaling-seurat")
install_github("BTIP2024/pca-seurat")
# library(writeseuratobject)
#library(qualitycontrolseurat)
#library(selectionscalingseurat)
#library(pcaseurat)
